### ISSUE TITLE
Remaining rebase launch items summary list

### ISSUE THREAD

**Issue by mattpass** [BTCPrivate/BTCP-Rebase#103]
This is simply a summary list of what remains to be done from a 30,000 ft high view so nothing is forgotten. This list can be added to/discussed so it's complete and covered by the rebase, in some rough order:

**Phase 1**
- [ ] RPC wallet - get Bitcoin RPC methods working (119 commands -119/119)
- [ ] All send transaction address types working, tested extensively

**Phase 2**
- [ ] RPC wallet - get ZCash RPC methods working (26 more commands - 145/145)
- [ ] Change from Equihash 144,5 to Equihash 192,7
- [ ] Add block reward changes

**Phase 3**
- [ ] Coin burn discussion & possibly details
- [ ] Update client wallets
- [ ] Review and action any remaining crucial issues to cover
- [ ] Get all tests in test dir working
- [ ] Perfect install setup and README.md & docs where needed
- [ ] Mark as v1.0.0 beta
- [ ] Ask community to test
- [ ] Fix any bugs, test everything again and go to release candidate

**Releasing rebase**
- [ ] Release info re hard fork blockheight, summary of rebase, upgrade guide, info on existing coins, nothing for community to do etc
- [ ] Ask exchanges etc to update
- [ ] Launch party
- [ ] Marketing to promote
